# Generated by Django 4.1.6 on 2023-02-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_car2'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='plate_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
