# Generated by Django 4.1.6 on 2023-02-13 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_car_plate_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car2',
        ),
    ]
