# Generated by Django 4.1.6 on 2023-02-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_person_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='renters',
            field=models.ManyToManyField(through='my_app.Rent', to='my_app.person'),
        ),
    ]
